function [BW,maskedImage] = segmentImage(image)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 05-Sep-2021
%----------------------------------------------------


X = im2uint16(image);

% Adjust data to span data range.
Xadj = imadjust(X);

% Auto clustering
%s = rng;
%rng('default');
%L = imsegkmeans(single(Xadj),2,'NumAttempts',2);
%rng(s);

%if sum(isnan(image(L==1))) > sum(isnan(image(L==2)))
    %BW = L == 2;
%else
   % BW = L == 1;
%end

% Create masked image.
%maskedImage = Xadj;
%maskedImage(~BW) = 0;


% Threshold image - adaptive threshold
BW = imbinarize(Xadj, 'adaptive', 'Sensitivity', 0.500000, 'ForegroundPolarity', 'bright');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

